language: python

env:
  global:
  - APPVEYOR_SLUG=sample-c-extension
  - APPVEYOR_ACCOUNT=agronholm
  # APPVEYOR_TOKEN
  - secure: kJ45l4UxhT1wgR+SHvAK/XfbJgo3ZI+0GCwFLaLjo/z6WQ5B7KAcT6ZYvpguiVYSfdWNtVTM2JMd1bSQs+ffqouOkrSYn0nWfOV/HP1Ip922/KW8bXDCDegspmzEM3GaJEKq4GUmnpTr/Ht6BP/4L3gpDKW7f5mxAKCaKAWr4MqMTH/rQKXxWUgXwjEHqhfbe/V5pLSVLFH8DjJGQoqkcQcOpAvzzJz2r6vPqdBzvNxP3v7mzysguGy21Wp7q7QSzzCKol+1eVGQ6zdAA93Msk8KWsNPG7QsiXyRO/bAiJslm3XIqykOt0XXnrM0xvpzLY7R22T75NnuH7/M2l4QgphT+DyH1FYnJDWMPV7bQG9GCNT+2AAUgojHJaxL9jFNho+2iTUrz6OX5ZTZrrT7a/PkJ/yhTR/IqKW9k10HVIHMLxjIOiEHzO6qwLY4gIYkhqqMJ+NOvO7tIVNlZnYHqs58ml461d1hNDAihPqDz0ZWwS35cNtvRX1l2Atog2sbNOsEb5Ckl4+jcFlioUnfBURZHThdNzn+GTWNy9jS017zc1C4XU/yVxsnZXIlwMTWBL+66m6RAsTMYTopb4AP9RGZKXMAJGUVOJhC54k8v2lGyJkK7cKuJUJsjJV4kr6DxKq4QN5VzAymNJjDzC+iBZFn3le8LTLiKKlpBXXOSKo=
  - AWS_ACCESS_KEY_ID=AKIAIMQCR46NDYBLBB5A
  # AWS_SECRET_ACCESS_KEY
  - secure: JriC5fWchIq0KTyEuUpeIsKp0IlBUdM467tPhCs6n3QLrYQJomB+onMa/jNV1FyEfIFIvOKdJRQQE6m1T1szzjTp5dLcwFctLGjr1JAeFIoW8Yz5sejyhV0jmzmyDHz4bL94+6cFYhsZ7wYvV/ktv8t/I8AFgzogTfX4KWMiBJL1Hr6DqpcvnIcRd5dlGJr6epKg5+s1P6XYsX6Q+amSYeimgmJnEYgfw1rarFVguqBSFxSTYZ1LP0fMwxRZbqsy8kCdW6Smi8J25amnayeeVl1+ToNhB56cCUZguIv8ZJ6rEVYymyVpR/xUA4JYEL4M+UfQd82kk6y3UDaMeUjjXJEN0trSb5tY9dFaOEKP4HbCAdzri6vlR2+3em8t0YXqb+WqIQA5H/HjzsfC/NC29T6gDW8BmyFy5McXwgzHZ6iLxNkAU45ZmRJBe0l+2IuWwLxza4TTBPGUftNCdf5yiNOQ8NEUQJWlEkt8gzPwm+vbINClVcirMQF1656dnq5J46CzRZAuNwQSoaohVc/EAQYG7DJT0UNryQqbie/pScMSlauBq6f0mvxe+n2Iu9TBqJvfEKR6pVr7dPz7FiX4oSVOq1K3M2h5UirLskJU69/U5ZJW9zh3KP75vNXWyCXeFfFhUMbGoeQo/aekHsv90oIf1ysEsuPPa9rnVtkzoeI=
  - TWINE_USERNAME=agronholm
  # TWINE_PASSWORD
  - secure: UtyY7ukxCKBgRSiNZezfvc72D3I0GhgEk1dwu3AzcQKFtH9REZsc/WqNbXCaRnWAhiUvodg49tGxduiA/7gDYT/1rwNxr+vipeYkEIppDPh9UD9V35M2WfrKSItx0GTZUsWIfAFT9eRqlGNtIKZ/vJpKsLE/Fwsvp3EkkhlZLECeEbP1k16qDNw1PjAbPgDDgt7VUNEGF+KhzFkLrkmogaa6whp5vR0nl05wFzTSspXuRfJ/NbKDEO7xxCwy/oK33b3vPMkxwijGhO5FG40/Sv44a31srBar3PvY+BPGBVPg0mxZRTGb2BZJGXXQNFhiSC+DpGiiryEVA35GM/xvEzQ3eg5h1e718ZNZ53jLCLgJBrjBuuDfUH+Kma0ZaT2w3CrOoBiF7aYbYO55EtIVdZ/LgDKZPclW2Vj0YyIpCH6dT4PZ+cuRoPT/hgXjmaT5M05vq/wQpgDvomTajMdkbsGW52IELN9gkGDXzd6/w+z77CrXfYXymOSzxxMqTUKED2E8RZWRM6FDLsZahTdDyfBGZSIWk9JPO06QvNqzHr0WeKOm1VKQzMBBXDO2x5D4uFGiC9pbQ73KOAnInPFI2nD8vPRQv45GTvLU+8EkD9OnI5Uto0hfnxoxfvhseZnLzH55DbyW0/HV4yW6TdJutkMFc9Goy9Y3l+aUhPOFhyI=

stages:
  - name: test
  - name: package sdist
    if: type = push AND tag ~= ^v\d+\.\d+\.\d+
  - name: package wheel
    if: type = push AND tag ~= ^v\d+\.\d+\.\d+
  - name: deploy to pypi
    if: type = push AND tag ~= ^v\d+\.\d+\.\d+

jobs:
  fast_finish: true
  include:
  - &test
    stage: test
    python: '2.7'
    install:
    - pip install Cython
    - pip install -e .[test]
    script: pytest

  - <<: *test
    python: '3.4'

  - <<: *test
    python: '3.5'

  - <<: *test
    python: '3.6'

  - stage: package sdist
    python: '3.5'
    before_install: &setup_s3
    - pip install awscli
    - mkdir dist
    install: pip install Cython
    script: python setup.py sdist
    after_success:
    - aws s3 rm --recursive s3://sample-c-extension/dist
    - aws s3 sync dist s3://sample-c-extension/dist

  # Linux
  - stage: package wheels
    env: OS=LINUX
    sudo: required
    before_install: *setup_s3
    install: skip
    script: docker run --rm -it -v $(pwd):/io -w /io quay.io/pypa/manylinux1_x86_64 .ci/build_linux_wheels.sh
    after_success: aws s3 sync wheelhouse s3://sample-c-extension/dist

  # macOS
  - stage: package wheels
    os: osx
    language: generic
    env: OS=MACOS
    before_install: *setup_s3
    script: .ci/build_macos_wheels.sh
    after_success: aws s3 sync dist s3://sample-c-extension/dist

  # Windows
  - stage: package wheels
    env: OS=WINDOWS
    before_install: *setup_s3
    install: pip install requests
    script: .ci/build_windows_wheels.py
    after_success: aws s3 sync wheelhouse s3://sample-c-extension/dist

  - stage: deploy to pypi
    before_install: *setup_s3
    install: pip install twine
    script:
    - aws s3 sync s3://sample-c-extension/dist dist
    - twine upload --repository-url https://test.pypi.org/legacy/ dist/*
    - aws s3 rm --recursive s3://sample-c-extension/dist
